version: '3.8'

services:
  db:
#    restart: unless-stopped
    image: postgres:13
    container_name: shortlink-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: shortlink
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./scripts:/docker-entrypoint-initdb.d
    networks:
      - backend
    ports:
      - "5432:5432"
    deploy:
      resources:
        limits:
          memory: 512M

  app:
#    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    container_name: shortlink-app
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: root
      DB_NAME: shortlink
    depends_on:
      - db
    networks:
      - backend
    ports:
      - "8000:8000"
    deploy:
      resources:
        limits:
          memory: 256M

  nginx:
    image: nginx
    container_name: shortlink-nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./website/static:/usr/share/nginx/html
    networks:
      - backend
      - frontend
    ports:
      - "80:80"
    depends_on:
      - app
    deploy:
      resources:
        limits:
          memory: 128M

volumes:
  pgdata:

networks:
  frontend:
  backend:
