version: '3.8'

services:
  db:
#    restart: unless-stopped
    image: postgres:13
    container_name: shortlink-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: shortlink
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./scripts:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

  app:
#    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    container_name: shortlink-app
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: root
      DB_NAME: shortlink
    depends_on:
      - db
    ports:
      - "8000:8000"

  nginx:
    image: nginx:latest
    container_name: shortlink-nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./website/static:/usr/share/nginx/html
    ports:
      - "80:80"
    depends_on:
      - app

volumes:
  pgdata:
